### ISSUE TITLE
Is it possible to add an extra output of kernel matrix for the forward modelling?

### ISSUE THREAD

**Issue by lianghcug** [fatiando/harmonica#229]
**Description of the desired feature**

In the latest version of harmonica.0.2.1, the output of the function to do forward modelling ("harmonica.prism_gravity" and "harmonica.tesseroid_gravity") is only the gravitational field. Is it possible to add an extra output of kernel matrix of the forward modelling? If so, we will be able to develop some inversion program based on the kernel matrix.

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by santisoler** [comment]
Hi @lianghcug! Thanks for opening this issue.

If I understood correctly, you want the `harmonica.prism_gravity()` and `harmonica.tesseroid_gravity()` functions to return the gravitational field and the kernel matrix `A`, where `A` is the matrix that relates the density of the bodies `m` with the resulting gravitational field `g`: `g = A · m`. Right?

I would say that we are not planning to implement this for two reasons:
1. The first one is because of design. The intentions of these two functions are to return only the gravitational field. This behavior is tight to the function names and the fact that most users won't be expecting a kernel matrix to be returned after a forward model computation.
2. The second one is more technical. We never allocate the entire kernel matrices. Both for prisms and tesseroids, the forward modelling is done iteratively. On each iteration, the corresponding kernel matrix element between the current computation point and body is computed on the fly, the gravitational field added to the final result (aggregator) and then all variables are discarded. The main reason of choosing this workflow is for saving memory. The kernel matrices grow too big too fast when the number of bodies and computation points are increased, so if we would store them in memory, we would be crushing systems every once in a while.

Nevertheless, you could compute the matrix elements by yourself, using the kernel functions. 
For example, for tesseroids, you could use the `gauss_legendre_quadrature` function to compute the kernel matrix element for a pair of observation point and tesseroid by passing a `density=1`:
https://github.com/fatiando/harmonica/blob/632d7aef543a1eabac520fc3f5a0bb0f8794bbba/harmonica/forward/tesseroid.py#L302

While for prisms, we have defined the kernel functions, although the kernel matrix element for each you need to compute the sums for each vertex of the prism:
https://github.com/fatiando/harmonica/blob/632d7aef543a1eabac520fc3f5a0bb0f8794bbba/harmonica/forward/prism.py#L226-L240

Maybe we could refactor the `jit_prism_gravity()` function by taking this sum into a different function so you can access it without having to rewrite some code.

**Comment by lianghcug** [comment]
> Hi @lianghcug! Thanks for opening this issue.
> 
> If I understood correctly, you want the `harmonica.prism_gravity()` and `harmonica.tesseroid_gravity()` functions to return the gravitational field and the kernel matrix `A`, where `A` is the matrix that relates the density of the bodies `m` with the resulting gravitational field `g`: `g = A · m`. Right?
> 
> I would say that we are not planning to implement this for two reasons:
> 
> 1. The first one is because of design. The intentions of these two functions are to return only the gravitational field. This behavior is tight to the function names and the fact that most users won't be expecting a kernel matrix to be returned after a forward model computation.
> 2. The second one is more technical. We never allocate the entire kernel matrices. Both for prisms and tesseroids, the forward modelling is done iteratively. On each iteration, the corresponding kernel matrix element between the current computation point and body is computed on the fly, the gravitational field added to the final result (aggregator) and then all variables are discarded. The main reason of choosing this workflow is for saving memory. The kernel matrices grow too big too fast when the number of bodies and computation points are increased, so if we would store them in memory, we would be crushing systems every once in a while.
> 
> Nevertheless, you could compute the matrix elements by yourself, using the kernel functions.
> For example, for tesseroids, you could use the `gauss_legendre_quadrature` function to compute the kernel matrix element for a pair of observation point and tesseroid by passing a `density=1`:
> https://github.com/fatiando/harmonica/blob/632d7aef543a1eabac520fc3f5a0bb0f8794bbba/harmonica/forward/tesseroid.py#L302
> 
> While for prisms, we have defined the kernel functions, although the kernel matrix element for each you need to compute the sums for each vertex of the prism:
> https://github.com/fatiando/harmonica/blob/632d7aef543a1eabac520fc3f5a0bb0f8794bbba/harmonica/forward/prism.py#L226-L240
> 
> Maybe we could refactor the `jit_prism_gravity()` function by taking this sum into a different function so you can access it without having to rewrite some code.
