### ISSUE TITLE
Source depth from radial average power spectrum

### ISSUE THREAD

**Issue by sissiautumn** [fatiando/harmonica#3]
**Description of the desired feature**
The Fatiando package provides an example using the Hawaii gravity data and computing the radial average of its power spectrum.
Is it possible to estimate the average source depth according to the radial average of the power spectrum? In fact, there are several papers mentioned this, even the uncertainty is still controversial. 
The equation is similar like h=(P(r1)-P(r2))/(4*pi*(r2-r1))

For a giving 2D anomaly (gravity or magnetic), we could get the radial average of the power spectrum and the possible source depths.

**Are you willing to help implement and maintain this feature?** Yes/No
Yes

**Comment by leouieda** [comment]
@sissiautumn thanks for opening the feature request! This will probably require #4 first.

I'll update this when I have the basis for the repository structured and we're ready to start implementing features.

**Comment by santisoler** [comment]
Since there are several methods of obtaining the source depth from the power spectrum, which are based on different assumptions and hypothesis, I don't think we should give a single complete solution to it in order to avoid its misuse. I'm closing this issue. Feel free to discuss further if you think otherwise.
