### ISSUE TITLE
Ignore prisms with user-defined volume/thickness threshold

### ISSUE THREAD

**Issue by mdtanker** [fatiando/harmonica#371]
**Description of the desired feature:**

As discussed in the meeting today ([notes](https://hackmd.io/@fatiando/development-calls-2022#2022-12-07)), it would be great to allow users to vary the threshold for prisms of low volume/thickness. Currently, as introduced in PR #334, prisms with no volume are ignored when `prism_gravity` is called to save some unnecessary computation. In my use case, there are many prisms that are thin, but not exactly equal to 0, and thus are contributing to the run time, but not affecting the results significantly. 

It would be helpful if users could change some threshold parameter to account for this. 

## Option 1: 
Currently, zero-volume prisms are defined by this [line](https://github.com/fatiando/harmonica/blob/9529b5ace1056128bce000d2f8b9e88dd2b9016c/harmonica/forward/prism.py#L242): 
```python
# Mark prisms with zero volume as null prisms
null_prisms = (west == east) | (south == north) | (bottom == top)
```
We could change this to something similar to: 
```python
null_prisms = (abs(west - east) <= ew_thres) | (abs(south - north) <= ns_thres) | (abs(bottom - top) <= thick_thres)
```
where `ew_thres`, `ns_thres`, and `thick_thres` all default to 0. This would allow users to vary if they wanted.

## Option 2: 
Suggested by @santisoler, we could also implement this within the `prism_layer.gravity()` function. I assume this could be implement the same as the Option 1 example above.

**Are you willing to help implement and maintain this feature?** 

Yes I'm happy to attempt this!

**Comment by santisoler** [comment]
Thanks @mdtanker for opening this issue!

I agree that it would be helpful to have some way to ignore small prisms in order to speed up the computations.

Giving you use case I think we need to make this option available in `prism_layer.gravity()`, otherwise it won't solve your particular problem. So now the question would be if `prism_layer.gravity()` should be the one that handles the ignore of those thin prisms or if `prism_gravity()` should the one that handles it.

In my opinion there aren't too many use cases for `prism_gravity()` to ignore small prisms: the effect of those prisms depends on the dimensions of the prism, but also on its density and the distance to the computation point. So for the general case it hard to set a threshold and be confident that the forward model is still accurate.

But for your particular use case the scenario is quite different: you already know the density values of your prisms in the layer, the distribution of the prisms in the layer is somewhat continuous and the observation points are going to be all at roughly the same distance to the layer (or without high variations). So in this case it makes sense that we could ignore thin prisms.

So, what if we start coding this in the `prism_layer.gravity()` method adding an optional parameter to it through which we can specify the thickness threshold of the prisms that will be ignored.

If we find any use case for ignoring small prisms in the general case we could implement it in `prism_gravity()` and then refactor `prism_layer.gravity()` to rely on it.

What do you think?

**Comment by mdtanker** [comment]
Yes, that sounds great to me. I will try and put something together within `prism_layer.gravity()` and open a PR for it.
